"""
Universo de activos — S&P 500 · IPC México · ETFs · Acciones Globales
Incluye acciones individuales, ETFs sectoriales, temáticos, apalancados y de renta fija.
El buscador también acepta cualquier ticker válido de Yahoo Finance fuera de este catálogo.
"""

STOCK_UNIVERSE = {

    # ══════════════════════════════════════════════════════════════════════
    # ETFs — MERCADO AMPLIO / ÍNDICES
    # ══════════════════════════════════════════════════════════════════════
    "SPY": {
        "name": "SPDR S&P 500 ETF Trust",
        "sector": "ETF — Mercado Amplio",
        "index": "ETF",
        "profile": ["conservative", "moderate", "aggressive"],
        "thesis": "El ETF más líquido del mundo, replica el S&P 500. Exposición diversificada a las 500 mayores empresas de EE.UU.; referencia estándar de la industria.",
        "currency": "USD",
    },
    "VOO": {
        "name": "Vanguard S&P 500 ETF",
        "sector": "ETF — Mercado Amplio",
        "index": "ETF",
        "profile": ["conservative", "moderate"],
        "thesis": "El ETF de menor costo que replica el S&P 500 (0.03% expense ratio). Ideal como núcleo de portafolio a largo plazo con mínimos costos de fricción.",
        "currency": "USD",
    },
    "QQQ": {
        "name": "Invesco QQQ Trust (Nasdaq-100)",
        "sector": "ETF — Tecnología / Nasdaq",
        "index": "ETF",
        "profile": ["moderate", "aggressive"],
        "thesis": "Réplica del Nasdaq-100, concentrado en las 100 mayores tecnológicas no financieras. Alta ponderación en IA, cloud y semiconductores; referencia de crecimiento de largo plazo.",
        "currency": "USD",
    },
    "QQQM": {
        "name": "Invesco Nasdaq-100 ETF (mini QQQ)",
        "sector": "ETF — Tecnología / Nasdaq",
        "index": "ETF",
        "profile": ["moderate", "aggressive"],
        "thesis": "Versión de menor denominación del QQQ con igual exposición al Nasdaq-100. Preferido por inversionistas individuales por su precio accesible y menor spread.",
        "currency": "USD",
    },
    "IVV": {
        "name": "iShares Core S&P 500 ETF",
        "sector": "ETF — Mercado Amplio",
        "index": "ETF",
        "profile": ["conservative", "moderate"],
        "thesis": "Alternativa de iShares al SPY con menor costo (0.03%). Estructura favorable para portafolios de largo plazo; tracking error mínimo respecto al benchmark.",
        "currency": "USD",
    },
    "VTI": {
        "name": "Vanguard Total Stock Market ETF",
        "sector": "ETF — Mercado Total EE.UU.",
        "index": "ETF",
        "profile": ["conservative", "moderate"],
        "thesis": "Exposición a más de 4,000 empresas estadounidenses de todos los tamaños. Máxima diversificación doméstica con sesgo hacia mid y small caps respecto al S&P 500.",
        "currency": "USD",
    },
    "RSP": {
        "name": "Invesco S&P 500 Equal Weight ETF",
        "sector": "ETF — S&P 500 Igual Peso",
        "index": "ETF",
        "profile": ["moderate"],
        "thesis": "S&P 500 con pesos iguales elimina la concentración en mega-caps. Históricamente supera al S&P 500 ponderado por capitalización en ciclos de rotación de valor.",
        "currency": "USD",
    },

    # ══════════════════════════════════════════════════════════════════════
    # ETFs — SEMICONDUCTORES
    # ══════════════════════════════════════════════════════════════════════
    "SOXX": {
        "name": "iShares Semiconductor ETF",
        "sector": "ETF — Semiconductores",
        "index": "ETF",
        "profile": ["moderate", "aggressive"],
        "thesis": "Exposición diversificada a los 30 mayores fabricantes y diseñadores de semiconductores. Incluye NVDA, AVGO, AMD, QCOM, TXN, INTC, AMAT. Benchmark del sector.",
        "currency": "USD",
    },
    "SOXL": {
        "name": "Direxion Daily Semiconductor Bull 3X ETF",
        "sector": "ETF — Semiconductores Apalancado 3x",
        "index": "ETF",
        "profile": ["aggressive"],
        "thesis": "ETF apalancado 3x al índice PHLX Semiconductor. Amplifica tanto ganancias como pérdidas; adecuado solo para operaciones de corto plazo con alta tolerancia al riesgo. No recomendado para buy-and-hold.",
        "currency": "USD",
    },
    "SOXS": {
        "name": "Direxion Daily Semiconductor Bear 3X ETF",
        "sector": "ETF — Semiconductores Inverso 3x",
        "index": "ETF",
        "profile": ["aggressive"],
        "thesis": "ETF inverso 3x al índice PHLX Semiconductor. Instrumento de cobertura o especulación bajista a corto plazo. El decaimiento temporal lo hace inadecuado para posiciones largas.",
        "currency": "USD",
    },
    "SMH": {
        "name": "VanEck Semiconductor ETF",
        "sector": "ETF — Semiconductores",
        "index": "ETF",
        "profile": ["moderate", "aggressive"],
        "thesis": "Alternativa a SOXX con mayor concentración en TSMC, NVDA y ASML. La exposición a manufactura global de chips añade un componente internacional diferenciado.",
        "currency": "USD",
    },

    # ══════════════════════════════════════════════════════════════════════
    # ETFs — TECNOLOGÍA / IA / DISRUPCIÓN
    # ══════════════════════════════════════════════════════════════════════
    "XLK": {
        "name": "Technology Select Sector SPDR ETF",
        "sector": "ETF — Tecnología",
        "index": "ETF",
        "profile": ["moderate", "aggressive"],
        "thesis": "ETF sectorial de tecnología del S&P 500. Alta concentración en AAPL, MSFT y NVDA. Referencia de la industria para exposición pura al sector tecnológico del S&P.",
        "currency": "USD",
    },
    "VGT": {
        "name": "Vanguard Information Technology ETF",
        "sector": "ETF — Tecnología",
        "index": "ETF",
        "profile": ["moderate", "aggressive"],
        "thesis": "Amplia exposición al sector IT con >300 empresas. Incluye hardware, software y servicios. Menor concentración que XLK con mejor diversificación intra-sectorial.",
        "currency": "USD",
    },
    "ARKK": {
        "name": "ARK Innovation ETF",
        "sector": "ETF — Innovación / Disrupción",
        "index": "ETF",
        "profile": ["aggressive"],
        "thesis": "Portafolio de gestión activa enfocado en tecnologías disruptivas: IA, robótica, edición genómica y fintech. Alta volatilidad y beta; orientado a horizontes de 5+ años.",
        "currency": "USD",
    },
    "BOTZ": {
        "name": "Global X Robotics & Artificial Intelligence ETF",
        "sector": "ETF — Robótica / IA",
        "index": "ETF",
        "profile": ["aggressive"],
        "thesis": "Exposición temática a empresas líderes en robótica, automatización e inteligencia artificial. Incluye Intuitive Surgical, ABB, FANUC y proveedores de NVIDIA.",
        "currency": "USD",
    },
    "CIBR": {
        "name": "First Trust NASDAQ Cybersecurity ETF",
        "sector": "ETF — Ciberseguridad",
        "index": "ETF",
        "profile": ["moderate", "aggressive"],
        "thesis": "Exposición diversificada a empresas de ciberseguridad. El crecimiento del gasto corporativo en seguridad es una tendencia estructural impulsada por regulación y amenazas crecientes.",
        "currency": "USD",
    },
    "TQQQ": {
        "name": "ProShares UltraPro QQQ (3x Nasdaq-100)",
        "sector": "ETF — Nasdaq Apalancado 3x",
        "index": "ETF",
        "profile": ["aggressive"],
        "thesis": "ETF apalancado 3x al Nasdaq-100. El decaimiento por volatilidad lo hace apropiado solo para swing trading o mercados tendenciales. Riesgo muy elevado en correcciones.",
        "currency": "USD",
    },
    "UPRO": {
        "name": "ProShares UltraPro S&P 500 (3x SPY)",
        "sector": "ETF — S&P 500 Apalancado 3x",
        "index": "ETF",
        "profile": ["aggressive"],
        "thesis": "ETF apalancado 3x al S&P 500. En mercados alcistas sostenidos supera ampliamente al índice; en correcciones las pérdidas se amplifican por el mismo factor.",
        "currency": "USD",
    },

    # ══════════════════════════════════════════════════════════════════════
    # ETFs — SECTORIALES (SPDR Select Sector)
    # ══════════════════════════════════════════════════════════════════════
    "XLE": {
        "name": "Energy Select Sector SPDR ETF",
        "sector": "ETF — Energía",
        "index": "ETF",
        "profile": ["moderate"],
        "thesis": "Las 23 empresas energéticas del S&P 500: XOM, CVX, COP, EOG, SLB. Sensible al precio del petróleo; dividendo atractivo y hedge natural contra la inflación.",
        "currency": "USD",
    },
    "XLF": {
        "name": "Financial Select Sector SPDR ETF",
        "sector": "ETF — Financiero",
        "index": "ETF",
        "profile": ["moderate"],
        "thesis": "Exposición al sector financiero del S&P 500: bancos, aseguradoras, gestoras. Beneficia de tasas elevadas y del ciclo de reapertura del crédito al consumo.",
        "currency": "USD",
    },
    "XLV": {
        "name": "Health Care Select Sector SPDR ETF",
        "sector": "ETF — Salud",
        "index": "ETF",
        "profile": ["conservative", "moderate"],
        "thesis": "Exposición defensiva al sector salud: farmacéuticas, biotecnología y dispositivos médicos. Beta bajo, baja correlación con el ciclo económico e ingresos predecibles.",
        "currency": "USD",
    },
    "XLI": {
        "name": "Industrial Select Sector SPDR ETF",
        "sector": "ETF — Industrial",
        "index": "ETF",
        "profile": ["moderate"],
        "thesis": "Empresas industriales del S&P 500: aeroespacial, maquinaria, transporte y defensa. Beneficia del ciclo de inversión en infraestructura y el reshoring manufacturero.",
        "currency": "USD",
    },
    "XLY": {
        "name": "Consumer Discretionary Select SPDR ETF",
        "sector": "ETF — Consumo Discrecional",
        "index": "ETF",
        "profile": ["moderate", "aggressive"],
        "thesis": "Empresas de consumo no esencial: AMZN, TSLA, HD, MCD, NKE. Alta correlación con el ciclo económico; se beneficia en expansiones y sufre en recesiones.",
        "currency": "USD",
    },
    "XLP": {
        "name": "Consumer Staples Select SPDR ETF",
        "sector": "ETF — Consumo Básico",
        "index": "ETF",
        "profile": ["conservative"],
        "thesis": "Empresas de consumo básico: PG, KO, WMT, COST, PEP. Alta defensividad; bajo beta y dividendo estable. Ancla de portafolio en entornos de incertidumbre.",
        "currency": "USD",
    },
    "XLU": {
        "name": "Utilities Select Sector SPDR ETF",
        "sector": "ETF — Utilities",
        "index": "ETF",
        "profile": ["conservative"],
        "thesis": "Empresas de servicios públicos regulados: NEE, DUK, SO, AEP. Beta muy bajo, alta rentabilidad por dividendo. Beneficia de recortes de tasas de interés.",
        "currency": "USD",
    },
    "XLRE": {
        "name": "Real Estate Select Sector SPDR ETF",
        "sector": "ETF — Bienes Raíces",
        "index": "ETF",
        "profile": ["conservative", "moderate"],
        "thesis": "REITs del S&P 500: PLD, AMT, EQIX, CCI. Alta rentabilidad por dividendo requerida por regulación; beneficia de la caída de tasas y demanda de data centers.",
        "currency": "USD",
    },
    "XLB": {
        "name": "Materials Select Sector SPDR ETF",
        "sector": "ETF — Materiales",
        "index": "ETF",
        "profile": ["moderate"],
        "thesis": "Empresas de materiales: Linde, Freeport-McMoRan, Air Products. Sensible al ciclo industrial y la demanda de minerales críticos para la transición energética.",
        "currency": "USD",
    },
    "XLC": {
        "name": "Communication Services Select SPDR ETF",
        "sector": "ETF — Comunicaciones",
        "index": "ETF",
        "profile": ["moderate", "aggressive"],
        "thesis": "Servicios de comunicación del S&P 500: META, GOOGL, NFLX, DIS, T, VZ. Mezcla de crecimiento en streaming y redes sociales con defensividad en telecomunicaciones.",
        "currency": "USD",
    },

    # ══════════════════════════════════════════════════════════════════════
    # ETFs — RENTA FIJA / BONOS
    # ══════════════════════════════════════════════════════════════════════
    "TLT": {
        "name": "iShares 20+ Year Treasury Bond ETF",
        "sector": "ETF — Bonos del Tesoro Largo Plazo",
        "index": "ETF",
        "profile": ["conservative"],
        "thesis": "Bonos del Tesoro de EE.UU. con vencimiento >20 años. Alta duración implica sensibilidad máxima a cambios de tasas. Correlación negativa con acciones en crisis.",
        "currency": "USD",
    },
    "AGG": {
        "name": "iShares Core U.S. Aggregate Bond ETF",
        "sector": "ETF — Renta Fija Agregada",
        "index": "ETF",
        "profile": ["conservative"],
        "thesis": "El benchmark de renta fija estadounidense: Tesoros, bonos corporativos investment grade y MBS. Ancla de baja volatilidad para portafolios balanceados.",
        "currency": "USD",
    },
    "HYG": {
        "name": "iShares iBoxx $ High Yield Corporate Bond ETF",
        "sector": "ETF — Bonos High Yield",
        "index": "ETF",
        "profile": ["moderate"],
        "thesis": "Bonos corporativos de alto rendimiento (sub-investment grade). Mayor yield que grado de inversión a cambio de riesgo crediticio; alta correlación con renta variable.",
        "currency": "USD",
    },
    "LQD": {
        "name": "iShares iBoxx $ Investment Grade Corporate Bond ETF",
        "sector": "ETF — Bonos Corporativos IG",
        "index": "ETF",
        "profile": ["conservative", "moderate"],
        "thesis": "Bonos corporativos investment grade de EE.UU. Spread de crédito sobre Tesoros con menor volatilidad que high yield. Diversificador de portafolio con flujo de caja estable.",
        "currency": "USD",
    },

    # ══════════════════════════════════════════════════════════════════════
    # ETFs — INTERNACIONALES / EMERGENTES
    # ══════════════════════════════════════════════════════════════════════
    "EWW": {
        "name": "iShares MSCI Mexico ETF",
        "sector": "ETF — México",
        "index": "ETF",
        "profile": ["moderate", "aggressive"],
        "thesis": "Exposición directa al mercado accionario mexicano: WALMEX, AMXL, FEMSA, Banorte. Beneficia del nearshoring y el crecimiento del consumo doméstico en México.",
        "currency": "USD",
    },
    "EEM": {
        "name": "iShares MSCI Emerging Markets ETF",
        "sector": "ETF — Mercados Emergentes",
        "index": "ETF",
        "profile": ["moderate", "aggressive"],
        "thesis": "Amplia exposición a mercados emergentes: China, India, Taiwán, Corea, Brasil. Diversificación geográfica con potencial de crecimiento superior al mundo desarrollado.",
        "currency": "USD",
    },
    "VWO": {
        "name": "Vanguard FTSE Emerging Markets ETF",
        "sector": "ETF — Mercados Emergentes",
        "index": "ETF",
        "profile": ["moderate"],
        "thesis": "Alternativa de Vanguard a EEM con menor costo. Incluye más de 5,000 empresas en mercados emergentes. Componente de diversificación global de largo plazo.",
        "currency": "USD",
    },
    "EFA": {
        "name": "iShares MSCI EAFE ETF",
        "sector": "ETF — Europa / Asia / Oceanía",
        "index": "ETF",
        "profile": ["conservative", "moderate"],
        "thesis": "Mercados desarrollados fuera de EE.UU. y Canadá: Europa, Japón, Australia. Diversificación de divisas; valuaciones generalmente más bajas que mercados estadounidenses.",
        "currency": "USD",
    },

    # ══════════════════════════════════════════════════════════════════════
    # ETFs — MATERIAS PRIMAS / COMMODITIES
    # ══════════════════════════════════════════════════════════════════════
    "GLD": {
        "name": "SPDR Gold Shares ETF",
        "sector": "ETF — Oro",
        "index": "ETF",
        "profile": ["conservative", "moderate"],
        "thesis": "Exposición directa al precio del oro físico. Reserva de valor, hedge inflacionario y activo refugio en crisis geopolíticas. Baja correlación con renta variable.",
        "currency": "USD",
    },
    "SLV": {
        "name": "iShares Silver Trust ETF",
        "sector": "ETF — Plata",
        "index": "ETF",
        "profile": ["moderate", "aggressive"],
        "thesis": "Exposición al precio de la plata física. Demanda industrial creciente (paneles solares, electrónica) además de la demanda monetaria. Mayor volatilidad que el oro.",
        "currency": "USD",
    },
    "PDBC": {
        "name": "Invesco Optimum Yield Diversified Commodity Strategy ETF",
        "sector": "ETF — Commodities Diversificado",
        "index": "ETF",
        "profile": ["moderate"],
        "thesis": "Cartera diversificada de futuros de commodities: energía, metales y agricultura. Hedge inflacionario amplio con optimización del roll yield para reducir contango.",
        "currency": "USD",
    },

    # ══════════════════════════════════════════════════════════════════════
    # ETFs — DIVIDENDOS / FACTOR / VOLATILIDAD
    # ══════════════════════════════════════════════════════════════════════
    "VYM": {
        "name": "Vanguard High Dividend Yield ETF",
        "sector": "ETF — Dividendos",
        "index": "ETF",
        "profile": ["conservative"],
        "thesis": "Empresas con dividendos por encima de la media del mercado. Exposición a financieras, energéticas y consumo básico. Portafolio de renta con menor volatilidad que el S&P 500.",
        "currency": "USD",
    },
    "SCHD": {
        "name": "Schwab US Dividend Equity ETF",
        "sector": "ETF — Dividendos de Calidad",
        "index": "ETF",
        "profile": ["conservative", "moderate"],
        "thesis": "Empresas con historial sólido de dividendos y fundamentos de calidad. Combina yield atractivo con criterios de solidez financiera. Uno de los ETFs de dividendo más eficientes en costos.",
        "currency": "USD",
    },
    "JEPI": {
        "name": "JPMorgan Equity Premium Income ETF",
        "sector": "ETF — Renta / Income",
        "index": "ETF",
        "profile": ["conservative"],
        "thesis": "Genera ingresos mensuales combinando acciones defensivas con opciones call cubiertas (covered calls). Yield mensual elevado a cambio de limitar el upside en mercados alcistas.",
        "currency": "USD",
    },

    # ══════════════════════════════════════════════════════════════════════
    # SEMICONDUCTORES — ACCIONES INDIVIDUALES
    # ══════════════════════════════════════════════════════════════════════
    "NVDA": {
        "name": "NVIDIA Corporation",
        "sector": "Semiconductores",
        "index": "S&P 500",
        "profile": ["aggressive"],
        "thesis": "Proveedor dominante de GPUs para IA generativa y centros de datos. La plataforma CUDA crea un moat profundo; backlog y guía de ingresos sin precedentes históricos.",
        "currency": "USD",
    },
    "AMD": {
        "name": "Advanced Micro Devices",
        "sector": "Semiconductores",
        "index": "S&P 500",
        "profile": ["aggressive"],
        "thesis": "Gana cuota en CPUs frente a Intel y en GPUs para data centers. La familia MI300X compite directamente en el segmento IA de alto crecimiento.",
        "currency": "USD",
    },
    "AVGO": {
        "name": "Broadcom Inc.",
        "sector": "Semiconductores",
        "index": "S&P 500",
        "profile": ["moderate", "aggressive"],
        "thesis": "Líder en semiconductores de red y almacenamiento. La adquisición de VMware añade software con márgenes del 70%+. Dividendo creciente y recompras activas.",
        "currency": "USD",
    },
    "QCOM": {
        "name": "Qualcomm Inc.",
        "sector": "Semiconductores",
        "index": "S&P 500",
        "profile": ["moderate", "aggressive"],
        "thesis": "Domina modems para smartphones y diversifica hacia IoT, automotriz y PC. Regalías por patentes generan ingresos recurrentes independientes del ciclo de ventas.",
        "currency": "USD",
    },
    "TXN": {
        "name": "Texas Instruments Inc.",
        "sector": "Semiconductores",
        "index": "S&P 500",
        "profile": ["conservative", "moderate"],
        "thesis": "Chips analógicos e integrados para industrial y automotriz. Dividendo con CAGR del 17% histórico y FCF excepcional gracias a manufactura internalizada.",
        "currency": "USD",
    },
    "INTC": {
        "name": "Intel Corporation",
        "sector": "Semiconductores",
        "index": "S&P 500",
        "profile": ["moderate"],
        "thesis": "En reestructuración hacia manufactura por contrato (Intel Foundry). Valoración comprimida respecto a pares ofrece upside asimétrico si el turnaround prospera.",
        "currency": "USD",
    },
    "MU": {
        "name": "Micron Technology Inc.",
        "sector": "Semiconductores",
        "index": "S&P 500",
        "profile": ["moderate", "aggressive"],
        "thesis": "Segundo fabricante global de DRAM y NAND. La demanda de memoria HBM3 para IAs es un catalizador secular. El ciclo alcista de memoria beneficia márgenes significativamente.",
        "currency": "USD",
    },
    "LRCX": {
        "name": "Lam Research Corporation",
        "sector": "Semiconductores / Equipos",
        "index": "S&P 500",
        "profile": ["moderate", "aggressive"],
        "thesis": "Líder en equipos de deposición y grabado. Excelente posicionamiento en chips de memoria 3D; ingresos de servicio recurrentes suavizan la ciclicidad del capex.",
        "currency": "USD",
    },
    "AMAT": {
        "name": "Applied Materials Inc.",
        "sector": "Semiconductores / Equipos",
        "index": "S&P 500",
        "profile": ["moderate", "aggressive"],
        "thesis": "Mayor proveedor de equipos de fabricación de semiconductores. La carrera global por capacidad de chips y servicios recurrentes mitigan la ciclicidad del sector.",
        "currency": "USD",
    },
    "KLAC": {
        "name": "KLA Corporation",
        "sector": "Semiconductores / Equipos",
        "index": "S&P 500",
        "profile": ["moderate"],
        "thesis": "Líder en equipos de inspección y metrología. Alta barrera de entrada y baja sustitución en el proceso de fabricación. Márgenes operativos del 35%+.",
        "currency": "USD",
    },
    "MRVL": {
        "name": "Marvell Technology Inc.",
        "sector": "Semiconductores",
        "index": "S&P 500",
        "profile": ["aggressive"],
        "thesis": "Diseñador de chips personalizados (ASIC) para IA en hiperescaladores. Silicon fotónico y portfolio de chips de red son diferenciadores clave frente a NVIDIA.",
        "currency": "USD",
    },
    "ON": {
        "name": "ON Semiconductor (onsemi)",
        "sector": "Semiconductores",
        "index": "S&P 500",
        "profile": ["moderate", "aggressive"],
        "thesis": "Especialista en semiconductores de potencia para EVs y energías renovables. La electrificación vehicular es un viento de cola de largo plazo.",
        "currency": "USD",
    },
    "NXPI": {
        "name": "NXP Semiconductors N.V.",
        "sector": "Semiconductores",
        "index": "S&P 500",
        "profile": ["moderate"],
        "thesis": "Líder en semiconductores automotrices e industriales. El aumento de contenido electrónico por vehículo impulsa el crecimiento orgánico sostenido.",
        "currency": "USD",
    },
    "LITE": {
        "name": "Lumentum Holdings Inc.",
        "sector": "Semiconductores / Fotónica",
        "index": "S&P 500",
        "profile": ["aggressive"],
        "thesis": "Componentes fotónicos y láseres para data centers y telecomunicaciones. La demanda de transceptores ópticos para redes IA es un catalizador de crecimiento.",
        "currency": "USD",
    },
    "SNDK": {
        "name": "Sandisk Corporation",
        "sector": "Semiconductores / Almacenamiento",
        "index": "S&P 500",
        "profile": ["moderate", "aggressive"],
        "thesis": "Fabricante de memoria flash NAND, spin-off de Western Digital. Posición líder en almacenamiento de consumo y empresarial; beneficia del superciclo de almacenamiento para IA.",
        "currency": "USD",
    },
    "WDC": {
        "name": "Western Digital Corporation",
        "sector": "Almacenamiento / Hardware",
        "index": "S&P 500",
        "profile": ["moderate"],
        "thesis": "Fabricante líder de HDDs y soluciones de almacenamiento. Tras el spin-off de NAND (SNDK), el negocio de disco duro se beneficia del crecimiento en data centers y nearline storage.",
        "currency": "USD",
    },
    "STX": {
        "name": "Seagate Technology Holdings",
        "sector": "Almacenamiento / Hardware",
        "index": "S&P 500",
        "profile": ["moderate"],
        "thesis": "Líder en discos duros (HDD) para data centers. La demanda de almacenamiento masivo para IA supera a la capacidad instalada; reiniciación del ciclo alcista en HDDs nearline.",
        "currency": "USD",
    },
    "ARM": {
        "name": "Arm Holdings plc",
        "sector": "Semiconductores / IP",
        "index": "S&P 500",
        "profile": ["aggressive"],
        "thesis": "Propietario de la arquitectura dominante en móviles (99%) y en expansión en data centers y automotriz. Modelo de royalties altamente escalable con cada nuevo chip.",
        "currency": "USD",
    },
    "ASML": {
        "name": "ASML Holding N.V.",
        "sector": "Semiconductores / Equipos",
        "index": "S&P 500",
        "profile": ["moderate", "aggressive"],
        "thesis": "Monopolio absoluto en litografía EUV. Sin ASML no existe chip avanzado: moat tecnológico insuperable. Cartera de pedidos multianual visible y en expansión.",
        "currency": "USD",
    },
    "NBIS": {
        "name": "Nebius Group N.V.",
        "sector": "IA / Infraestructura Cloud",
        "index": "Global",
        "profile": ["aggressive"],
        "thesis": "Plataforma de infraestructura de IA con clústeres GPU de alta densidad en Europa. Spin-off del negocio internacional de Yandex; posicionada como alternativa europea a AWS/Azure para cargas de IA.",
        "currency": "USD",
    },

    # ══════════════════════════════════════════════════════════════════════
    # TECNOLOGÍA — SOFTWARE / CLOUD / IA
    # ══════════════════════════════════════════════════════════════════════
    "AAPL": {
        "name": "Apple Inc.",
        "sector": "Tecnología",
        "index": "S&P 500",
        "profile": ["moderate", "aggressive"],
        "thesis": "Ecosistema cerrado con altísima retención; servicios en expansión. Recompra de acciones récord y posición dominante en hardware premium global.",
        "currency": "USD",
    },
    "MSFT": {
        "name": "Microsoft Corporation",
        "sector": "Tecnología",
        "index": "S&P 500",
        "profile": ["moderate", "aggressive"],
        "thesis": "Azure crece >20% YoY; Copilot monetiza el catálogo de 300M+ usuarios. Ingresos recurrentes en la nube con visibilidad de largo plazo.",
        "currency": "USD",
    },
    "GOOGL": {
        "name": "Alphabet Inc.",
        "sector": "Tecnología",
        "index": "S&P 500",
        "profile": ["moderate", "aggressive"],
        "thesis": "Monopolio de búsqueda con >90% de cuota. Google Cloud se acelera; Gemini y DeepMind consolidan el liderazgo en IA con valoración razonable.",
        "currency": "USD",
    },
    "META": {
        "name": "Meta Platforms Inc.",
        "sector": "Tecnología / Social Media",
        "index": "S&P 500",
        "profile": ["aggressive"],
        "thesis": "3.3B de usuarios activos; monetización de Reels y WhatsApp en etapa temprana. Capex en IA convierte el feed en motor de alto ROI para anunciantes.",
        "currency": "USD",
    },
    "AMZN": {
        "name": "Amazon.com Inc.",
        "sector": "Tecnología / Cloud",
        "index": "S&P 500",
        "profile": ["moderate", "aggressive"],
        "thesis": "AWS genera >70% del beneficio operativo. Publicidad crece a doble dígito alto. Compresión de costos logísticos amplía márgenes hacia niveles estructurales.",
        "currency": "USD",
    },
    "CRM": {
        "name": "Salesforce Inc.",
        "sector": "Software / Cloud",
        "index": "S&P 500",
        "profile": ["moderate"],
        "thesis": "Líder en CRM empresarial con Agentforce como motor de crecimiento de IA. Mejora de márgenes y recompras intensivas sustentan la revalorización del múltiplo.",
        "currency": "USD",
    },
    "NOW": {
        "name": "ServiceNow Inc.",
        "sector": "Software / Cloud",
        "index": "S&P 500",
        "profile": ["moderate", "aggressive"],
        "thesis": "Automatización empresarial con retención del 98%+. La integración de IA en workflows aumenta el valor por contrato y acelera la adopción.",
        "currency": "USD",
    },
    "ADBE": {
        "name": "Adobe Inc.",
        "sector": "Software / Creatividad",
        "index": "S&P 500",
        "profile": ["moderate"],
        "thesis": "Domina el software creativo con Creative Cloud. Firefly y herramientas de IA generativa protegen el moat y amplían ARPU sin afectar la retención.",
        "currency": "USD",
    },
    "ORCL": {
        "name": "Oracle Corporation",
        "sector": "Software / Cloud",
        "index": "S&P 500",
        "profile": ["moderate"],
        "thesis": "OCI acelera con contratos GPU para IA. La base instalada de bases de datos empresariales es casi imposible de sustituir; recurrencia estructural del revenue.",
        "currency": "USD",
    },
    "INTU": {
        "name": "Intuit Inc.",
        "sector": "Software / Fintech",
        "index": "S&P 500",
        "profile": ["moderate"],
        "thesis": "TurboTax y QuickBooks dominan SMBs en EE.UU. Credit Karma integra datos financieros. Altísima retención y modelo de suscripción predecible.",
        "currency": "USD",
    },
    "PANW": {
        "name": "Palo Alto Networks",
        "sector": "Software / Ciberseguridad",
        "index": "S&P 500",
        "profile": ["moderate", "aggressive"],
        "thesis": "Líder en seguridad cloud con Prisma y Cortex. La consolidación de proveedores favorece plataformas integradas; ARR de $4B+ crece >20% anual.",
        "currency": "USD",
    },
    "SNOW": {
        "name": "Snowflake Inc.",
        "sector": "Software / Data Cloud",
        "index": "S&P 500",
        "profile": ["aggressive"],
        "thesis": "Plataforma de datos en la nube con modelo de consumo. Snowpark y Cortex AI amplían el TAM; NRR históricamente por encima del 120%.",
        "currency": "USD",
    },
    "TSLA": {
        "name": "Tesla Inc.",
        "sector": "Consumo Discrecional / EVs",
        "index": "S&P 500",
        "profile": ["aggressive"],
        "thesis": "Líder en EVs con red de Superchargers como ventaja. Robotaxi y FSD añaden opcionalidad significativa al modelo de valoración a largo plazo.",
        "currency": "USD",
    },
    "NFLX": {
        "name": "Netflix Inc.",
        "sector": "Comunicaciones / Streaming",
        "index": "S&P 500",
        "profile": ["moderate", "aggressive"],
        "thesis": "270M+ suscriptores; nivel de publicidad en aceleración. Gaming y live events amplían el modelo. FCF robusto financia contenido y recompras activas.",
        "currency": "USD",
    },

    # ══════════════════════════════════════════════════════════════════════
    # HARDWARE / INFRAESTRUCTURA
    # ══════════════════════════════════════════════════════════════════════
    "DELL": {
        "name": "Dell Technologies Inc.",
        "sector": "Hardware / Infraestructura",
        "index": "S&P 500",
        "profile": ["moderate"],
        "thesis": "Principal proveedor de servidores PowerEdge con GPUs NVIDIA para IA. ISG crece >30% YoY; valoración deprimida respecto al crecimiento de beneficios.",
        "currency": "USD",
    },
    "HPE": {
        "name": "Hewlett Packard Enterprise",
        "sector": "Hardware / Infraestructura",
        "index": "S&P 500",
        "profile": ["moderate"],
        "thesis": "Servidores, almacenamiento y GreenLake para empresas. El backlog de sistemas de IA crece; dividendo sostenido y recompras activas.",
        "currency": "USD",
    },
    "CSCO": {
        "name": "Cisco Systems Inc.",
        "sector": "Redes / Infraestructura",
        "index": "S&P 500",
        "profile": ["conservative", "moderate"],
        "thesis": "Domina switches y routers empresariales. Transición a software y suscripciones mejora la recurrencia. Dividendo sólido y recompras constantes.",
        "currency": "USD",
    },

    # ══════════════════════════════════════════════════════════════════════
    # ENERGÍA
    # ══════════════════════════════════════════════════════════════════════
    "XOM": {
        "name": "Exxon Mobil Corporation",
        "sector": "Energía",
        "index": "S&P 500",
        "profile": ["conservative", "moderate"],
        "thesis": "Mayor integrada de petróleo de EE.UU. FCF robusto incluso a precios bajos del crudo; 40+ años consecutivos de incrementos en el dividendo.",
        "currency": "USD",
    },
    "CVX": {
        "name": "Chevron Corporation",
        "sector": "Energía",
        "index": "S&P 500",
        "profile": ["conservative", "moderate"],
        "thesis": "Balance sólido y una de las menores estructuras de costo por barril. Permian Basin y proyectos LNG garantizan producción creciente; dividendo Aristocrat.",
        "currency": "USD",
    },
    "COP": {
        "name": "ConocoPhillips",
        "sector": "Energía",
        "index": "S&P 500",
        "profile": ["moderate"],
        "thesis": "E&P de bajo costo con fuerte exposición al Permian y Alaska. Disciplina de capital ejemplar con programa de retorno al accionista vía dividendos + recompras.",
        "currency": "USD",
    },
    "SLB": {
        "name": "SLB (Schlumberger)",
        "sector": "Servicios Energéticos",
        "index": "S&P 500",
        "profile": ["moderate"],
        "thesis": "Mayor empresa de servicios petroleros del mundo. El ciclo de inversión en upstream offshore es un catalizador multi-año; expansión en geotermia y CCS.",
        "currency": "USD",
    },
    "EOG": {
        "name": "EOG Resources Inc.",
        "sector": "Energía",
        "index": "S&P 500",
        "profile": ["moderate"],
        "thesis": "E&P de alta calidad en cuencas de bajo costo de EE.UU. Retornos sobre capital superiores al sector; dividendos ordinarios más dividendos especiales recurrentes.",
        "currency": "USD",
    },
    "OXY": {
        "name": "Occidental Petroleum",
        "sector": "Energía",
        "index": "S&P 500",
        "profile": ["moderate", "aggressive"],
        "thesis": "Principal operador en el Permian con tecnología de captura de carbono (DAC). Berkshire Hathaway como accionista ancla otorga credibilidad estratégica.",
        "currency": "USD",
    },
    "PSX": {
        "name": "Phillips 66",
        "sector": "Energía / Refinación",
        "index": "S&P 500",
        "profile": ["conservative", "moderate"],
        "thesis": "Refinería y midstream con márgenes más estables que E&P puro. La conversión de refinerías a combustibles renovables abre fuentes de ingresos regulados.",
        "currency": "USD",
    },
    "NEE": {
        "name": "NextEra Energy Inc.",
        "sector": "Utilities / Energías Renovables",
        "index": "S&P 500",
        "profile": ["conservative"],
        "thesis": "Mayor generador de energía eólica y solar del mundo. Pipeline de proyectos por décadas asegurado; dividendo con CAGR del 10% histórico.",
        "currency": "USD",
    },

    # ══════════════════════════════════════════════════════════════════════
    # FARMACÉUTICA / BIOTECNOLOGÍA / SALUD
    # ══════════════════════════════════════════════════════════════════════
    "LLY": {
        "name": "Eli Lilly and Company",
        "sector": "Farmacéutica",
        "index": "S&P 500",
        "profile": ["moderate", "aggressive"],
        "thesis": "Tirzepatida domina el mercado de obesidad y diabetes. El pipeline —Orforglipron oral, donanemab— extiende la visibilidad de crecimiento por años.",
        "currency": "USD",
    },
    "JNJ": {
        "name": "Johnson & Johnson",
        "sector": "Salud",
        "index": "S&P 500",
        "profile": ["conservative"],
        "thesis": "Dividend Aristocrat con 60+ años de incrementos. Pipeline en oncología e inmunología; dispositivos médicos de alto valor con demanda inelástica.",
        "currency": "USD",
    },
    "UNH": {
        "name": "UnitedHealth Group",
        "sector": "Salud / Seguros",
        "index": "S&P 500",
        "profile": ["conservative", "moderate"],
        "thesis": "Integración vertical en salud (seguro + Optum) crea moat difícil de replicar. Crecimiento demográfico como catalizador secular.",
        "currency": "USD",
    },
    "PFE": {
        "name": "Pfizer Inc.",
        "sector": "Farmacéutica",
        "index": "S&P 500",
        "profile": ["conservative", "moderate"],
        "thesis": "Valoración comprimida post-COVID con pipeline oncológico robusto (Seagen). Dividendo elevado y política activa de M&A estratégico.",
        "currency": "USD",
    },
    "MRK": {
        "name": "Merck & Co. Inc.",
        "sector": "Farmacéutica",
        "index": "S&P 500",
        "profile": ["conservative", "moderate"],
        "thesis": "Keytruda domina la inmunoterapia oncológica con $25B+ en ventas. Pipeline de vacunas y antibióticos mitiga el riesgo de expiración de patente.",
        "currency": "USD",
    },
    "ABBV": {
        "name": "AbbVie Inc.",
        "sector": "Farmacéutica",
        "index": "S&P 500",
        "profile": ["conservative", "moderate"],
        "thesis": "Skyrizi y Rinvoq sustituyen exitosamente a Humira. Pipeline oncológico robusto; dividendo elevado con baja correlación al ciclo económico.",
        "currency": "USD",
    },
    "AMGN": {
        "name": "Amgen Inc.",
        "sector": "Biotecnología",
        "index": "S&P 500",
        "profile": ["conservative", "moderate"],
        "thesis": "Pionero en bioterapéuticos con Repatha y Evenity. MariTide en obesidad podría ser el próximo catalizador. FCF robusto y dividendo creciente.",
        "currency": "USD",
    },
    "GILD": {
        "name": "Gilead Sciences Inc.",
        "sector": "Biotecnología",
        "index": "S&P 500",
        "profile": ["conservative", "moderate"],
        "thesis": "Domina el tratamiento de VIH con lenacapavir de larga duración. La oncología (Trodelvy) es el próximo motor de crecimiento. Valoración atractiva.",
        "currency": "USD",
    },
    "REGN": {
        "name": "Regeneron Pharmaceuticals",
        "sector": "Biotecnología",
        "index": "S&P 500",
        "profile": ["moderate", "aggressive"],
        "thesis": "Dupixent lidera el mercado de inflamación tipo 2. La plataforma VelociSuite acelera el descubrimiento de nuevas moléculas con alta tasa de éxito.",
        "currency": "USD",
    },
    "VRTX": {
        "name": "Vertex Pharmaceuticals",
        "sector": "Biotecnología",
        "index": "S&P 500",
        "profile": ["moderate", "aggressive"],
        "thesis": "Monopolio en fibrosis quística con Trikafta. Casgevy (terapia génica con CRISPR) abre un TAM nuevo en enfermedades raras.",
        "currency": "USD",
    },
    "ISRG": {
        "name": "Intuitive Surgical Inc.",
        "sector": "Dispositivos Médicos",
        "index": "S&P 500",
        "profile": ["moderate", "aggressive"],
        "thesis": "Monopolio en cirugía robótica con Da Vinci. Base instalada de 9,000+ sistemas genera ingresos recurrentes de consumibles con márgenes en expansión.",
        "currency": "USD",
    },
    "MDT": {
        "name": "Medtronic plc",
        "sector": "Dispositivos Médicos",
        "index": "S&P 500",
        "profile": ["conservative", "moderate"],
        "thesis": "Mayor fabricante de dispositivos médicos del mundo. Reestructuración centrada en márgenes; dividendo Aristocrat con crecimiento constante.",
        "currency": "USD",
    },

    # ══════════════════════════════════════════════════════════════════════
    # SERVICIOS FINANCIEROS
    # ══════════════════════════════════════════════════════════════════════
    "JPM": {
        "name": "JPMorgan Chase & Co.",
        "sector": "Servicios Financieros",
        "index": "S&P 500",
        "profile": ["conservative", "moderate"],
        "thesis": "Banco más grande de EE.UU. Gestión de riesgo ejemplar; diversificación en banca de inversión, consumo y gestión de activos.",
        "currency": "USD",
    },
    "GS": {
        "name": "Goldman Sachs Group",
        "sector": "Banca de Inversión",
        "index": "S&P 500",
        "profile": ["moderate", "aggressive"],
        "thesis": "Reapertura del ciclo de M&A impulsa comisiones. El retorno al core —mercados y gestión de activos— mejora el ROE estructuralmente.",
        "currency": "USD",
    },
    "MS": {
        "name": "Morgan Stanley",
        "sector": "Servicios Financieros",
        "index": "S&P 500",
        "profile": ["moderate"],
        "thesis": "Gestión patrimonial con $6T+ en AUM aporta estabilidad; banca de inversión añade beta al alza en ciclos expansivos.",
        "currency": "USD",
    },
    "V": {
        "name": "Visa Inc.",
        "sector": "Pagos Digitales",
        "index": "S&P 500",
        "profile": ["moderate"],
        "thesis": "Red de pagos sin riesgo crediticio. El duopolio Visa-Mastercard procesa >50% del comercio global. Digitalización del efectivo es tendencia secular.",
        "currency": "USD",
    },
    "MA": {
        "name": "Mastercard Inc.",
        "sector": "Pagos Digitales",
        "index": "S&P 500",
        "profile": ["moderate"],
        "thesis": "Codomina los pagos globales. Servicios de valor añadido (analytics, ciberseguridad, open banking) amplían márgenes y reducen la dependencia de volumen.",
        "currency": "USD",
    },
    "BRK-B": {
        "name": "Berkshire Hathaway B",
        "sector": "Conglomerado / Financiero",
        "index": "S&P 500",
        "profile": ["conservative", "moderate"],
        "thesis": "Portafolio diversificado con el mejor track record histórico. El float de seguros financia adquisiciones a bajo costo. Fortaleza en entornos volátiles.",
        "currency": "USD",
    },
    "SPGI": {
        "name": "S&P Global Inc.",
        "sector": "Servicios Financieros / Datos",
        "index": "S&P 500",
        "profile": ["moderate"],
        "thesis": "Duopolio en calificaciones crediticias y proveedor dominante de índices y datos financieros. Modelo de licencias con moat regulatorio difícil de replicar.",
        "currency": "USD",
    },
    "BLK": {
        "name": "BlackRock Inc.",
        "sector": "Gestión de Activos",
        "index": "S&P 500",
        "profile": ["moderate"],
        "thesis": "Mayor gestor de activos con $10T+ en AUM. iShares domina el mercado de ETFs. Plataforma Aladdin genera ingresos recurrentes de software.",
        "currency": "USD",
    },
    "AXP": {
        "name": "American Express Co.",
        "sector": "Servicios Financieros / Pagos",
        "index": "S&P 500",
        "profile": ["moderate"],
        "thesis": "Network cerrada con márgenes superiores. Millennials adoptan AmEx premium; ticket promedio por transacción es 3x vs Visa.",
        "currency": "USD",
    },

    # ══════════════════════════════════════════════════════════════════════
    # CONSUMO BÁSICO / DEFENSIVO / INDUSTRIAL
    # ══════════════════════════════════════════════════════════════════════
    "PG": {
        "name": "Procter & Gamble Co.",
        "sector": "Consumo Básico",
        "index": "S&P 500",
        "profile": ["conservative"],
        "thesis": "Portafolio de marcas esenciales con poder de fijación de precios. Beta bajo; demanda inelástica al ciclo económico. Dividendo fiable y creciente.",
        "currency": "USD",
    },
    "KO": {
        "name": "The Coca-Cola Company",
        "sector": "Consumo Básico",
        "index": "S&P 500",
        "profile": ["conservative"],
        "thesis": "Brand equity #1 global en bebidas, 200+ países. Márgenes estables y dividendo sin interrupciones desde 1893. Ancla defensiva ideal.",
        "currency": "USD",
    },
    "COST": {
        "name": "Costco Wholesale Corp.",
        "sector": "Consumo Básico / Retail",
        "index": "S&P 500",
        "profile": ["conservative", "moderate"],
        "thesis": "Modelo de membresía con retención excepcional. Capacidad de absorber inflación mejor que competidores gracias a rotación de inventario superior.",
        "currency": "USD",
    },
    "WMT": {
        "name": "Walmart Inc.",
        "sector": "Consumo Básico / Retail",
        "index": "S&P 500",
        "profile": ["conservative"],
        "thesis": "Mayor minorista del mundo. El segmento publicitario y financiero son catalizadores emergentes de alto margen sobre una base establecida.",
        "currency": "USD",
    },
    "TGT": {
        "name": "Target Corporation",
        "sector": "Consumo Discrecional / Retail",
        "index": "S&P 500",
        "profile": ["moderate"],
        "thesis": "Modelo omnicanal con marcas propias de alto margen. Normalización de inventarios y reducción de costos mejoran la rentabilidad operativa.",
        "currency": "USD",
    },
    "HD": {
        "name": "The Home Depot Inc.",
        "sector": "Consumo Discrecional / Retail",
        "index": "S&P 500",
        "profile": ["moderate"],
        "thesis": "Líder en mejoras del hogar; envejecimiento del parque habitacional impulsa la demanda. Cadena de suministro integrada y cliente Pro de alto valor.",
        "currency": "USD",
    },
    "MCD": {
        "name": "McDonald's Corporation",
        "sector": "Restaurantes",
        "index": "S&P 500",
        "profile": ["conservative"],
        "thesis": "Modelo de franquicias con ingresos recurrentes de bajo riesgo. Digitalización del pedido y delivery amplían márgenes; resistente en recesiones.",
        "currency": "USD",
    },
    "NKE": {
        "name": "Nike Inc.",
        "sector": "Consumo Discrecional / Ropa",
        "index": "S&P 500",
        "profile": ["moderate"],
        "thesis": "Marca deportiva más poderosa del mundo. Canal directo (DTC) amplía márgenes; renovación del portafolio y recuperación en China como catalizadores.",
        "currency": "USD",
    },
    "LMT": {
        "name": "Lockheed Martin Corporation",
        "sector": "Defensa & Aeroespacial",
        "index": "S&P 500",
        "profile": ["conservative", "moderate"],
        "thesis": "Contratos de largo plazo con el gobierno de EE.UU. y aliados OTAN. Expansión del gasto en defensa global como viento de cola estructural.",
        "currency": "USD",
    },
    "RTX": {
        "name": "RTX Corporation",
        "sector": "Defensa & Aeroespacial",
        "index": "S&P 500",
        "profile": ["conservative", "moderate"],
        "thesis": "Pratt & Whitney y Raytheon dan exposición dual al ciclo commercial y defensivo. Backlog de $200B+ asegura visibilidad de largo plazo.",
        "currency": "USD",
    },
    "CAT": {
        "name": "Caterpillar Inc.",
        "sector": "Maquinaria / Industrial",
        "index": "S&P 500",
        "profile": ["moderate"],
        "thesis": "Mayor fabricante de maquinaria pesada del mundo. Infraestructura y minería de minerales críticos como catalizadores seculares. Dividendo Aristocrat.",
        "currency": "USD",
    },
    "DE": {
        "name": "Deere & Company",
        "sector": "Maquinaria / Agricultura",
        "index": "S&P 500",
        "profile": ["moderate"],
        "thesis": "Domina la maquinaria agrícola de precisión. John Deere Operations Center genera ingresos recurrentes por software. Barrera tecnológica creciente.",
        "currency": "USD",
    },

    # ══════════════════════════════════════════════════════════════════════
    # IPC MÉXICO
    # ══════════════════════════════════════════════════════════════════════
    "AMXL.MX": {
        "name": "América Móvil",
        "sector": "Telecomunicaciones",
        "index": "IPC",
        "profile": ["conservative", "moderate"],
        "thesis": "Operador líder en Latinoamérica con >300M de clientes. FCF recurrente; expansión de fibra óptica mejora márgenes operativos.",
        "currency": "MXN",
    },
    "WALMEX.MX": {
        "name": "Walmart de México (WALMEX)",
        "sector": "Consumo Básico / Retail",
        "index": "IPC",
        "profile": ["conservative"],
        "thesis": "Líder absoluto del retail en México. E-commerce y expansión en CEDIS mejoran la rentabilidad por m² sostenidamente.",
        "currency": "MXN",
    },
    "FEMSAUBD.MX": {
        "name": "FEMSA",
        "sector": "Consumo Básico / Bebidas",
        "index": "IPC",
        "profile": ["conservative", "moderate"],
        "thesis": "Holding con embotellado (Coca-Cola FEMSA), farmacéutico (Femsa Salud) y OXXO. Crecimiento orgánico robusto y expansión latinoamericana.",
        "currency": "MXN",
    },
    "GFNORTEO.MX": {
        "name": "Grupo Financiero Banorte",
        "sector": "Servicios Financieros",
        "index": "IPC",
        "profile": ["moderate"],
        "thesis": "Banco más rentable de México con ROE >20%. El nearshoring impulsa la demanda de crédito corporativo.",
        "currency": "MXN",
    },
    "CEMEXCPO.MX": {
        "name": "CEMEX",
        "sector": "Materiales / Cemento",
        "index": "IPC",
        "profile": ["moderate", "aggressive"],
        "thesis": "Tercer productor de cemento global. Beneficio de infraestructura y vivienda; desapalancamiento mejora el perfil de riesgo crediticio.",
        "currency": "MXN",
    },
    "BIMBOA.MX": {
        "name": "Grupo Bimbo",
        "sector": "Consumo Básico / Alimentos",
        "index": "IPC",
        "profile": ["conservative"],
        "thesis": "Empresa de panificación más grande del mundo en 33 países. Demanda inelástica y poder de fijación de precios sostenido.",
        "currency": "MXN",
    },
    "GMEXICOB.MX": {
        "name": "Grupo México",
        "sector": "Minería / Cobre",
        "index": "IPC",
        "profile": ["moderate", "aggressive"],
        "thesis": "Tercer productor de cobre del mundo; el cobre es insumo crítico en la transición energética y EVs. Infraestructura ferroviaria añade estabilidad.",
        "currency": "MXN",
    },
    "GRUMAB.MX": {
        "name": "Gruma",
        "sector": "Consumo Básico / Alimentos",
        "index": "IPC",
        "profile": ["conservative", "moderate"],
        "thesis": "Líder global en tortilla y harina de maíz. La demografía latina en Norteamérica es un catalizador de largo plazo.",
        "currency": "MXN",
    },
    "ASURB.MX": {
        "name": "Grupo Aeroportuario del Sureste (ASUR)",
        "sector": "Infraestructura / Aeropuertos",
        "index": "IPC",
        "profile": ["moderate"],
        "thesis": "Concesiones aeroportuarias de largo plazo en el Caribe. El Tren Maya eleva el tráfico; tarifas ajustadas a inflación protegen ingresos reales.",
        "currency": "MXN",
    },
    "GAPB.MX": {
        "name": "Grupo Aeroportuario del Pacífico (GAP)",
        "sector": "Infraestructura / Aeropuertos",
        "index": "IPC",
        "profile": ["moderate"],
        "thesis": "Aeropuertos en Guadalajara y Puerto Vallarta. El nearshoring aumenta tráfico de negocios; tarifas indexadas a inflación protegen ingresos.",
        "currency": "MXN",
    },
    "KIMBERA.MX": {
        "name": "Kimberly-Clark de México",
        "sector": "Consumo Básico",
        "index": "IPC",
        "profile": ["conservative"],
        "thesis": "Líder en papel tissue y cuidado personal. Alta generación de FCF, dividendo consistente y baja volatilidad, ideal para portafolios defensivos.",
        "currency": "MXN",
    },
    "ORBIA.MX": {
        "name": "Orbia",
        "sector": "Materiales / Soluciones Industriales",
        "index": "IPC",
        "profile": ["moderate", "aggressive"],
        "thesis": "Conglomerado industrial con exposición a agua, nutrición vegetal, infraestructura de datos y polímeros. Diversificación geográfica mitiga riesgos cíclicos.",
        "currency": "MXN",
    },
    "OMAB.MX": {
        "name": "Grupo Aeroportuario Centro Norte (OMA)",
        "sector": "Infraestructura / Aeropuertos",
        "index": "IPC",
        "profile": ["moderate"],
        "thesis": "13 terminales en el norte de México. El nearshoring es un catalizador directo de tráfico industrial; tarifas indexadas a inflación.",
        "currency": "MXN",
    },
    "LIVEPOLC-1.MX": {
        "name": "El Puerto de Liverpool",
        "sector": "Consumo Discrecional / Retail",
        "index": "IPC",
        "profile": ["moderate"],
        "thesis": "Líder en tiendas departamentales de lujo en México. El segmento financiero (crédito al consumo) genera ingresos recurrentes de alto margen.",
        "currency": "MXN",
    },
    "CHDRAUIB.MX": {
        "name": "Grupo Chedraui",
        "sector": "Consumo Básico / Retail",
        "index": "IPC",
        "profile": ["conservative", "moderate"],
        "thesis": "Supermercados en México y EE.UU. (El Super). El crecimiento en el segmento hispano de EE.UU. es un catalizador geográfico diferenciado.",
        "currency": "MXN",
    },
    "TLEVISACPO.MX": {
        "name": "TelevisaUnivision",
        "sector": "Comunicaciones / Media",
        "index": "IPC",
        "profile": ["moderate", "aggressive"],
        "thesis": "Mayor conglomerado de media en español. ViX (streaming) en expansión con 45M+ de suscriptores potenciales en el mercado hispano de EE.UU.",
        "currency": "MXN",
    },
    "MEGACPO.MX": {
        "name": "Megacable Holdings",
        "sector": "Telecomunicaciones / Cable",
        "index": "IPC",
        "profile": ["moderate"],
        "thesis": "Operador de cable y broadband en México con red de fibra en expansión. La penetración de internet de alta velocidad en ciudades secundarias es el catalizador clave.",
        "currency": "MXN",
    },
}


PROFILE_CONFIG = {
    "conservative": {
        "label": "Conservador",
        "description": "Preservar capital con rendimientos estables y mínima volatilidad.",
        "max_weight": 0.20, "min_stocks": 6, "max_stocks": 10,
        "target_vol": 0.12, "risk_free_rate": 0.045, "color": "#10b981",
    },
    "moderate": {
        "label": "Moderado",
        "description": "Balance entre crecimiento y control del riesgo a largo plazo.",
        "max_weight": 0.25, "min_stocks": 6, "max_stocks": 10,
        "target_vol": 0.18, "risk_free_rate": 0.045, "color": "#3b82f6",
    },
    "aggressive": {
        "label": "Agresivo",
        "description": "Maximizar el rendimiento asumiendo mayor volatilidad.",
        "max_weight": 0.30, "min_stocks": 5, "max_stocks": 8,
        "target_vol": 0.30, "risk_free_rate": 0.045, "color": "#f59e0b",
    },
}


def get_tickers_for_profile(profile: str) -> list:
    return [t for t, d in STOCK_UNIVERSE.items() if profile in d["profile"]]
